[package]
name = "serde-save"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.198"

[dev-dependencies]
valuable = "0.1.0"
